VoiceReading/routes.py
"""Main routes."""
import os
from flask import Blueprint, render_template, redirect, url_for, request, send_from_directory, jsonify
from flask import current_app as app
from .assets import compile_assets
from werkzeug.utils import secure_filename
import time
import json
from .functions import get_voices, text_to_sv_speech, add_voice, play_voice, text_to_sv_speech_multi_speaker

# Blueprint Configuration
main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
compile_assets(app)


@main_bp.route('/', methods=['GET'])
def index():
    voices = get_voices()
    return render_template('index.jinja2',
                           refresh=str(int(round(time.time() * 1000))),
                           voices=voices)


@main_bp.route('/create', methods=['GET'])
def create():
    voices = get_voices()
    return render_template('create.jinja2',
                           refresh=str(int(round(time.time() * 1000))),
                           voices=voices)


@main_bp.route('/create_voice', methods=['POST'])
def create_voice():
    voice_name = request.form['voice_name']
    rand_pref = str(int(round(time.time() * 1000)))
    audio1 = request.files['audio1']
    if audio1:
        add_voice(audio1, voice_name, 1)
        #filename = rand_pref + '_file_1_' + voice_name + '.wav'
        #audio1.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    audio2 = request.files['audio2']
    if audio2:
        add_voice(audio2, voice_name, 2)
        #filename = rand_pref + '_file_2_' + voice_name + '.wav'
        #audio2.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    audio3 = request.files['audio3']
    if audio3:
        add_voice(audio3, voice_name, 3)
        # filename = rand_pref + '_file_3_' + voice_name + '.wav'
        # audio3.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    return redirect(url_for('main_bp.create'))


@main_bp.route('/upload_record', methods=['POST'])
def upload_record():
    file_audio = request.files['audio_data']

    # Upload
    filename = str(int(round(time.time() * 1000))) + '_record_' + request.form['index'] + '_' + secure_filename(file_audio.filename) + '.wav'
    file_audio.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    res = {
        "success": True,
        "message": "Success."
    }
    return jsonify(res)


@main_bp.route('/speech_all', methods=['POST'])
def speech_all():
    print(request.form['sentence_data'])
    form_data = json.loads(request.form['sentence_data'])
    #out_fpath = text_to_sv_speech(form_data)
    out_fpath = text_to_sv_speech_multi_speaker(form_data)
    print("audio path: {}".format(out_fpath))

    return send_from_directory(app.config['TTS_FOLDER_URL']
                               , out_fpath
                               , attachment_filename=out_fpath
                               , as_attachment=True)


@main_bp.route('/speech_sentence', methods=['POST'])
def speech_sentence():
    print(request.form['sentence_data'])
    form_data = json.loads(request.form['sentence_data'])
    voice_name = form_data[0]["voice"]
    out_fpath = play_voice(voice_name)

    return app.config['SPEECH_FOLDER_URL'] + '/' + out_fpath

VoiceReading/templates/create.jinja2
{% extends "layout.jinja2" %}

{% block content %}
    <form method="post" action="{{ url_for('main_bp.create_voice') }}" name="form_create" id="form_create" enctype="multipart/form-data">
        <div class="row gutters control-container">
            <div class="col">
                <div class="input-panel">
                    <select name="voice" id="voice">
                        <option value="0">Select Voice</option>
                        {% for voice in voices %}
                            <option value="{{ voice }}">{{ voice }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col">
                <div class="input-panel">
                    <input type="text" name="voice_name" id="voice_name" placeholder="Enter voice name" required>
                </div>
            </div>
            <div class="col">
                <div class="voice-controls">
                    <div class="voice-control">
                        <span class="fileinput-block">
                            <input type="file" class="inp-audio" name="audio1" id="audio1" accept="audio/wav">
                        </span>
                    </div>
                    <div class="voice-control">
                        <a href="#" class="btn-record" data-recording="false" data-index="1">
                            <img src="{{ url_for('static', filename='dist/img/mic.png') }}">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="voice-controls">
                    <div class="voice-control">
                        <span class="fileinput-block">
                            <input type="file" class="inp-audio" name="audio2" id="audio2" accept="audio/wav">
                        </span>
                    </div>
                    <div class="voice-control">
                        <a href="#" class="btn-record" data-recording="false" data-index="2">
                            <img src="{{ url_for('static', filename='dist/img/mic.png') }}">
                        </a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="voice-controls">
                    <div class="voice-control">
                        <span class="fileinput-block">
                            <input type="file" class="inp-audio" name="audio3" id="audio3" accept="audio/wav">
                        </span>
                    </div>
                    <div class="voice-control">
                        <a href="#" class="btn-record" data-recording="false" data-index="3">
                            <img src="{{ url_for('static', filename='dist/img/mic.png') }}">
                        </a>
                    </div>
                </div>
            </div>
            <div>
                <button type="submit" class="btn btn-main">
                    <img src="{{ url_for('static', filename='dist/img/play.png') }}">
                    CREATE
                </button>
            </div>
        </div>
        <input type="hidden" name="record1" value="">
        <input type="hidden" name="record2" value="">
        <input type="hidden" name="record3" value="">
    </form>
    <form method="post" id="form-text" name="form_text" action="{{ url_for('main_bp.speech_all') }}">
        <div class="text-container">
            <div class="text-panel">
                <div id="main_text" class="main_text" contenteditable="true">
                </div>
            </div>
            <div class="control-panel">
                <button class="btn btn-main">
                    <img src="{{ url_for('static', filename='dist/img/play.png') }}">
                    Convert & Download
                </button>
            </div>
        </div>
        <input type="hidden" name="sentence_data">
    </form>
    <div class="control-template d-none">
        <div class="side-controls" data-index="-1">
            <a href="#" class="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="{{ url_for('static', filename='dist/img/mic.png') }}">
            </a>
            <div class="dropdown-menu">
                <h6 class="dropdown-header">Apply different voice</h6>
                {% for voice in voices %}
                    <button class="dropdown-item" type="button">{{ voice }}</button>
                {% endfor %}
            </div>
            <a href="#" class="play-sentence">
                <img src="{{ url_for('static', filename='dist/img/play-circle.png') }}">
            </a>
        </div>
    </div>

    <audio id="sentence-audio" src=""></audio>
{% endblock %}

VoiceReading/templates/index.jinja2
{% extends "layout.jinja2" %}

{% block content %}
    <form method="post">
        <div class="row gutters control-container">
            <div class="col-3">
                <div class="input-panel">
                    <select name="voice" id="voice">
                        <option value="0">Select Voice</option>
                        {% for voice in voices %}
                            <option value="{{ voice }}">{{ voice }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-3">
                <a href="{{ url_for('main_bp.create') }}" class="btn-round">
                    <img src="{{ url_for('static', filename='dist/img/head.png') }}">
                    Create New Voice
                </a>
            </div>
        </div>
    </form>
    <form method="post" id="form-text" name="form_text" action="{{ url_for('main_bp.speech_all') }}">
        <div class="text-container">
            <div class="text-panel">
                <div id="main_text" class="main_text" contenteditable="true">
                </div>
            </div>
            <div class="control-panel">
                <button class="btn btn-main">
                    <img src="{{ url_for('static', filename='dist/img/play.png') }}">
                    Convert & Download
                </button>
            </div>
        </div>
        <input type="hidden" name="sentence_data">
    </form>
    <div class="control-template d-none">
        <div class="side-controls" data-index="-1">
            <a href="#" class="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="{{ url_for('static', filename='dist/img/mic.png') }}">
            </a>
            <div class="dropdown-menu">
                <h6 class="dropdown-header">Apply different voice</h6>
                {% for voice in voices %}
                    <button class="dropdown-item" type="button">{{ voice }}</button>
                {% endfor %}
            </div>
            <a href="#" class="play-sentence">
                <img src="{{ url_for('static', filename='dist/img/play-circle.png') }}">
            </a>
        </div>
    </div>

    <audio id="sentence-audio" src=""></audio>
{% endblock %}

VoiceReading/templates/layout.jinja2
<!doctype html>
<html lang="en">
<head>
    <title>Voice Reading</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="noindex">

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Muli:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='src/less/style.css') }}?{{ refresh }}" />
    {% block pagestyles %}{% endblock %}
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main_bp.index') }}">
            <img src="{{ url_for('static', filename='dist/img/logo.jpg') }}" alt="">
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
            </ul>
        </div>
    </div>
</nav>

<main role="main" class="container">
    {% block content %}{% endblock %}
</main><!-- /.container -->

<footer>
    &nbsp;
</footer>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% block scripts %}{% endblock %}
<script src="{{ url_for('static', filename='src/js/app.js') }}?{{ refresh }}"></script>
<script src="{{ url_for('static', filename='dist/js/recorder.js') }}"></script>
</body>
</html>